# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-01 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServPermssions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mall', models.IntegerField(choices=[(0, '未启用'), (1, '已启用'), (2, '锁定')], default=0, help_text='商城')),
                ('blog', models.BooleanField(choices=[(0, '未启用'), (1, '已启用'), (2, '锁定')], default=0, help_text='博客')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('mobile', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='servpermssions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
